server
    listen 127.0.0.1:8080
    server_name localhost
    root ./www
    index index.html
    error_page 403 /errors/403.html
    error_page 405 /errors/405.html
    error_page 409 /errors/409.html
    client_max_body_size 2M

    location /Delete
        methods GET DELETE
        autoindex on    
        root ./www

    location /images 
        methods POST 
        upload_store ./uploads

    location /cgi-bin 
        cgi_pass /usr/bin/python3
