server
    listen 127.0.0.1:8080
    server_name localhost
    root www
    error_page 403 srcs/Server/errors/403.html
    error_page 405 srcs/Server/errors/405.html
    error_page 409 srcs/Server/errors/409.html
    error_page 404 srcs/Server/errors/404.html
    error_page 400 srcs/Server/errors/400.html
    error_page 200 srcs/Server/errors/200.html
    client_max_body_size 2M

    location /
        autoindex on
        methods GET DELETE POST
        root ./www
        upload_store ./uploads
        return 200 "Welcome to the server!\n"

    location /images 
        methods POST 
        upload_store ./uploads

    location /cgi-bin 
        cgi_pass /usr/bin/python3
