server
    listen 127.0.0.1:8080
    server_name localhost
    root ./www
    index index.html
    error_page 404 ./errors/404.html
    client_max_body_size 2M

    location /
        methods GET POST
        autoindex on
        root ./www

    location /images 
        methods POST
        upload_store ./uploads

    location /cgi-bin 
        cgi_pass /usr/bin/python3        
server
    listen 127.0.0.1:8080
    server_name localhost
    root ./www
    index idx.html
    error_page 305 ./errors/404.html
    client_max_body_size 1M

    location /
        methods DELETE
        autoindex on

    location /upload 
        methods POST
        upload_store ./uploads

    location /cgi-bin 
        cgi_pass /usr/bin/python3
